### ISSUE TITLE
problem when use softserial nextion with sd library

### ISSUE THREAD

**Issue by jhonoryza** [DanNixon/NeoNextion#15]
i got problem, i cannot read file with sd library when use nextion in softwareserial mode
if (!SD.begin(10)) {
    Serial.println("initialization failed!");
    return;
  }
this code run fine, but cannot read or write file when i use nex.init() 

this is part of my code:
  
nextionSerial.begin(9600);
  nex.init();
  Serial.begin(9600);
  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }
  Serial.print("Initializing SD card...");
  if (!SD.begin(10)) {
    Serial.println("initialization failed!");
    return;
  }
  Serial.println("initialization done.");

**Comment by DanNixon** [comment]
I'm assuming you didn't change the pins used for software serial, one of which is pin 10.
This is expected in this case as you are trying to use the same pin for multiple functions.
Either use a different pin for software serial RX or use a different pin for SD chip select.

**Comment by jhonoryza** [comment]
for softwareserial i use 
SoftwareSerial nextionSerial(8, 9); // RX, TX
for initialization sd card works fine, but i can't open files (read or write) them, if i disable nextion function  i can open files, it seems nextion library and sd card library cannot be used at the same time

**Comment by DanNixon** [comment]
Does it work using hardware serial and SD card simultaneously?

**Comment by jhonoryza** [comment]
everything works fine if i use hardware serial, and there's about 87% space used for memory, but when i change to softwareserial the problems occur,
here's my full code http://pastebin.com/g22d9uiU

**Comment by DanNixon** [comment]
You are almost certainly running out of memory.
This is nothing to do with this library.

You can optimise this by storing your strings in program memory and using standard char arrays instead of the Arduino `String` which (at least used to) cause heap fragmentation leading to allocation issues.
