### ISSUE TITLE
BaudRate

### ISSUE THREAD

**Issue by acb01** [DanNixon/NeoNextion#20]
Is there some way to adjust (increase) the actual baudrate from 9600 to 115200?

**Comment by DanNixon** [comment]
Yes, it is a system variable that is configured in the same way as the backlight intensity.

Current value: `baud`

Default value: `bauds`

(https://www.itead.cc/wiki/Nextion_Instruction_Set#Nextion_HMI:_System_Variables_List)

**Comment by acb01** [comment]
Thank you very much Dan...

**Comment by ririfonfon** [comment]
Serial.println(nex.setbauds(115200));
     Serial.println(nex.getbaud());

exit status 1
'class Nextion' has no member named 'setbauds'

**Comment by DanNixon** [comment]
That shouldn't work, I never implemented it because the use case does not exist.

**Comment by ririfonfon** [comment]
Why the use case does not exist.
Pass the baud to 115200 should make the screen more reactive?

**Comment by ririfonfon** [comment]
Did you try to change it ?

**Comment by DanNixon** [comment]
You would only ever do this once and you wouldn't do it once the display is installed in a project so there is little use in the library doing it.

I haven't really got time for implementing features that will not get used often.
It should be possible, have a look at the way brightness is handled, baud rate seems to be exactly the same.

**Comment by ririfonfon** [comment]
ok thank you
