### ISSUE TITLE
NextionPage page.show() not working

### ISSUE THREAD

**Issue by mijnsleutel** [DanNixon/NeoNextion#21]
Hi,

In version 2.2.0 the show page command is not functioning correctly anymore. If i switch back to 2.1.0 everything is working fine.

Thank you !

**Comment by DanNixon** [comment]
Thanks for the report, I can see why this is happening but won't be able to push a fix until some time either this weekend of next week.

It's a result of the page validation code that only sends commands when on the correct page for a widget, which is never the case when calling `NextionPage::show()`.

**Comment by mijnsleutel** [comment]
Great ! no problem, we can develop with all features from 2.1.0. Thank you

-Mike

**Comment by top4ek** [comment]
Got same problem too on 2.0.0.

**Comment by DanNixon** [comment]
@top4ek The code in question is not in version 2.0.0

**Comment by top4ek** [comment]
2.2.0 doesn't works too, but anyway, it seems to be problem is related to SoftwareSerial, it doesn't works even with raw command.

**Comment by top4ek** [comment]
Yep, my fault. 
Display and ESP MUST be connected to common GND(didn't knew that). 2.0.0 works fine, 2.2 — doesn't.

**Comment by DanNixon** [comment]
See b3ab4cd.
