### ISSUE TITLE
identify which button I release

### ISSUE THREAD

**Issue by ririfonfon** [DanNixon/NeoNextion#22]
Hello dan,
I want to identify which button I release

I understood your function
If (type == NEX_EVENT_POP)

But then I would identify id of the buton

Type:
Switch (id) {
  case 1:
  // do something when var equals 1
       break;
Etc ...

Your buton.ino example
Uses a single button
So I deepened your .h and .cpp

In InextionWidget.ccp
I saw the command:
Uint8_t INextionWidget :: getComponentID ()
{
   return m_componentID;
}

But I do not understand how to integrate it in my code for the arduino

Please be indulgent with me, I am a beginner in c ++

thank you

And bravo for your work.

I work with your version 2.2
Editor arduino 1.8.1
Nextion 2.8 '' screen
And an arduino due

**Comment by DanNixon** [comment]
A pointer to the widget that generated the event is passed to the callback, you can call [`getComponentID()`](https://dannixon.github.io/NeoNextion/classINextionWidget.html#aaf32a37324c5f9c4bcae689b9f451595) on this to get it's unique ID.

**Comment by ririfonfon** [comment]
void callback(NextionEventType type, INextionTouchable *widget)
{
  if (type == NEX_EVENT_POP)
componentID = (INextionWidget::getComponentID());
   Serial.println("ID *widget = ");
   Serial.println(componentID);   
}

return error : 
exit status 1
cannot call member function 'uint8_t INextionWidget::getComponentID()' without object

**Comment by DanNixon** [comment]
You need to call it on the `widget` pointer, like this `uint8_t componentID = widget->getComponentID();`

**Comment by ririfonfon** [comment]
oh yes 
thank you
