### ISSUE TITLE
bauds and baud

### ISSUE THREAD

**Issue by ririfonfon** [DanNixon/NeoNextion#23]
Hello dan,
Would it be possible to add the functions bauds set and baud set.

https://www.itead.cc/wiki/Nextion_Instruction_Set#Nextion_HMI:_System_Variables_List

thank you in advance

Ps: I'm using NeoNextion-2.2.0

**Comment by DanNixon** [comment]
See #20.

TL;DR: yes, but no.

**Comment by ririfonfon** [comment]
oh ok 
thank you
