### ISSUE TITLE
setText() is too slow

### ISSUE THREAD

**Issue by top4ek** [DanNixon/NeoNextion#25]
Method setText() of NextionText class works too slow.
Four commands like `temp_1.setText(charVal);` are running about 3-4 seconds but four iterations of
```
    nextionSerial.print("temp_1.txt=\"");
    nextionSerial.print(charVal);
    nextionSerial.print("\"");
    nextionSerial.write(0xFF);
    nextionSerial.write(0xFF);
    nextionSerial.write(0xFF);
```
works almost instanly.

**Comment by DanNixon** [comment]
The library does validation and error checking which has to wait for a response from the display driver.
If time is important then Nextion displays are a bad choice.
