### ISSUE TITLE
Global scoped objects

### ISSUE THREAD

**Issue by ghirlekar** [DanNixon/NeoNextion#26]
I can't seem to find how to use objects with global scope. 

In the Nextion editor, if I want to access the globals object 'y' of a page 'x', I'd do x.y.txt="test". In NeoNextion, I found the following snippet of code in the sendCommand function

``` 
if (m_pageID != m_nextion.getCurrentPage())
    return false;
```

Am I right in assuming this means I cannot access attributes of globally scoped objects?

**Comment by DanNixon** [comment]
That would have been the case, yes.
I've just removed this checking, it seems it causes more issues than it is worth.

To be honest I still can't see the use case for modifying something that isn't on the current page.
