### ISSUE TITLE
Dual licensing under LGPL or BSD

### ISSUE THREAD

**Issue by s-celles** [DanNixon/NeoNextion#58]
Hello,

following discussion https://github.com/itead/ITEADLIB_Arduino_Nextion/issues/48#issuecomment-622996937

I'm wondering if @DanNixon could dual licence
https://github.com/DanNixon/NeoNextion under LGPL or BSD

The Arduino IDE is GPL but the Arduino Core is LGPL so it doesn't force user to use GPL for there own work (they can if they want but they can decide to use an other license LGPL, BSD or even proprietary if they wish).
I like GPL softwares but prefer LGPL libraries.

See https://www.arduino.cc/en/Main/FAQ#toc3
What do you mean by open-source hardware?

Kind regards

**Comment by DanNixon** [comment]
There isn't a particularly strong reason to re-license.

I don't expect people to be using this library in any setting, rather just hobby projects (after all, that is all the Nextion displays area actually suitable for).

Also just to be clear, this library is unmaintained now.

**Comment by s-celles** [comment]
Your code... your choices
Thanks anyway @DanNixon for your prompt answer
