### ISSUE TITLE
Support Particle devices

### ISSUE THREAD

**Issue by DanNixon** [DanNixon/NeoNextion#8]
itead/ITEADLIB_Arduino_Nextion#3 suggests this should be an easy fix.

I have a few Spark devices so would be worth adding.

**Comment by ddutchie** [comment]
I just received 2 photon devices and will be using one with a Nextion 7Inch. Great

**Comment by DanNixon** [comment]
When I started using mine I found it was a pain to actually use them, I've kind of converted to the ESP8266 anyway for cheap WiFi enabled dev boards so probably won't work on this much more.

**Comment by DanNixon** [comment]
@ddutchie Did you ever get a chance to try this with Particle devices? If so can you confirm if they work?
